#! /bin/sh
# /etc/init.d/vision

### BEGIN INIT INFO
# Provides:          vision
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Simple script to start a program at boot
# Description:       A simple script from www.stuffaboutcode.com which will start / stop a program a boot / shutdown.
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting vision"
    # run application you want to start
    nohup /home/pi/Desktop/FRC3620_2015_SnakeEyes/processcameraimages.py &
    ;;
  stop)
    echo "Stopping vision"
    # kill application you want to stop
    killall processcameraimages.py
    ;;
  *)
    echo "Usage: /etc/init.d/vision {start|stop}"
    exit 1
    ;;
esac

exit 0
